Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04ff98ccbfa41c9ad
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my,inst,from,cloudformation]]